### ISSUE TITLE
('-error: no file ', 'model/dnn/binhmm.SID')

### ISSUE THREAD

**Issue by wangwei20140722** [shun60s/Wave-DNN-likelihood#1]
when i run Wave-DNN-likelihood-master/read_binhmm.py,
('-error: no file ', 'model/dnn/binhmm.SID')
How can I get this file?

Then could you change your document in English?

**Comment by shun60s** [comment]
Regarding to model/dnn/binhmm.SID:
You can get in https://github.com/julius-speech/julius
Or, it' in https://github.com/julius-speech/dictation-kit/tree/master/model/dnn

No idea translate documents into English.
